# Generated by Django 3.1.5 on 2021-01-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('heading0', models.CharField(default='', max_length=500)),
                ('heading1', models.CharField(default='', max_length=500)),
                ('heading2', models.CharField(default='', max_length=500)),
                ('publish_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
